### ISSUE TITLE
ImportTicks operation will 413 if the user has too many ticks

### ISSUE THREAD

**Issue by drosseau** [OpenBeta/openbeta-graphql#405]
The `ImportTicks` operation will 413 if the user has too many ticks. For example I have 700+ and it failed for me. The response is just `Payload Too Large`. I also noticed the user's UUID is repeated for every tick; it could probably be pulled out to the base of the request?

**Comment by vnugent** [comment]
Fixed in #421 @drosseau I could successfully import ~2K ticks.  Can you try again?

**Comment by musoke** [comment]
I am still getting an error - it is unclear to me if it is the same error.

> Sorry, something went wrong. Please check your network and try again.

**Comment by vnugent** [comment]
Can you share a profile to help reproduce the issue? (via private communication ok)
